/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
 import clases.HelperInv;
import clases.Inventario;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.io.ObjectOutputStream;
import java.util.Calendar;

/**
 *
 * @author Lenovo
 */
public class InventarioIn extends javax.swing.JDialog {
    String rutaP;
    ObjectOutputStream salida;
    ArrayList<Inventario> inventario;
    int aux = 0;
    /**
     * Creates new form Inventario
     */
    public InventarioIn(java.awt.Frame parent, boolean modal) {
        
         super(parent, modal);
           try {
            initComponents();
            rutaP = "src/datos/inventario.txt";
            inventario = HelperInv.traerDatos2(rutaP);
            salida = new ObjectOutputStream(new FileOutputStream(rutaP));
            HelperInv.volcado2(salida, inventario);
            HelperInv.limpiadoTabla(tblInventario);
            HelperInv.llenarTabla2(tblInventario, rutaP);
            JButton botonesH[] = {cmdBuscar, cmdCancelar};
            JButton botonesD[] = {cmdAgregar, cmdEliminar};
            HelperInv.habilitarBotones(botonesH);
            HelperInv.deshabilitarBotones(botonesD);

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cmbFecha = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdAgregar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Marca:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));
        jPanel2.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, -1));

        jLabel3.setText("Nombre Producto:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, -1));

        jLabel4.setText("Cantidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, -1));

        jLabel5.setText("Clase:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perecederos", "No. Perecederos" }));
        jPanel2.add(cmbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, -1));

        jLabel6.setText("Fecha:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 90, 20));

        cmbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFechaActionPerformed(evt);
            }
        });
        jPanel2.add(cmbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 20, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 230, 210));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdAgregar.setText("Guardar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 100, -1));

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, -1));

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 100, -1));

        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 230, 180));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Personas"));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Marca", "Nombre Producto", "Cantidad", "Fecha Opcional ", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInventario);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 430, 360));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 450, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/abstract-wallpaper-1080p-186.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed

        try {
            String marca, nombreP,cantidad,fechaV,Tipo;
            marca= txtMarca.getText();
            nombreP = txtNombre.getText();
            cantidad = txtCantidad.getText();
            fechaV =jDateChooser1.getDateFormatString();
            Tipo= cmbtipo.getSelectedItem().toString();
            ArrayList<Inventario> actualizarProducto;

            if (aux == 0) {

                Inventario p = new Inventario(marca, nombreP,cantidad,fechaV,Tipo);
                p.guardar(salida);
                HelperInv.llenarTabla2(tblInventario, rutaP);
                txtNombre.setText("");
                txtMarca.setText("");
                txtCantidad.setText("");
                txtMarca.requestFocusInWindow();

            } else {
                actualizarProducto = HelperInv.actualizarProducto(rutaP, marca,nombreP,cantidad,fechaV,Tipo);
                salida = new ObjectOutputStream(new FileOutputStream(rutaP));
                HelperInv.volcado2(salida, actualizarProducto);
                HelperInv.llenarTabla2(tblInventario, rutaP);
                HelperInv.mensaje(this, "Datos actulizados exitosamente", "Correcto!", 1);

                limpiar();

            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdAgregar, cmdEliminar};
        HelperInv.habilitarBotones(botonesH);
        HelperInv.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;

        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            try {
                i = tblInventario.getSelectedRow();
                inventario.remove(i);
                salida = new ObjectOutputStream(new FileOutputStream(rutaP));
                HelperInv.volcado2(salida, inventario);
                HelperInv.llenarTabla2(tblInventario, rutaP);
                txtNombre.setText("");
                txtMarca.setText("");
                txtCantidad.setText("");
                txtMarca.requestFocusInWindow();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdAgregar, cmdEliminar};
        HelperInv.habilitarBotones(botonesH);
        HelperInv.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        limpiar();
        JButton botonesH[] = {cmdBuscar, cmdCancelar};
        JButton botonesD[] = {cmdAgregar, cmdEliminar};
        HelperInv.habilitarBotones(botonesH);
        HelperInv.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String Marca;
        Marca = txtMarca.getText();

        if (HelperInv.buscarMarca(Marca, rutaP)) {
            Inventario p = HelperInv.traerDatos2(Marca, rutaP);
            txtNombre.setText(p.getNombrep());
            txtCantidad.setText(p.getCantidad());
            jDateChooser1.setDateFormatString(p.getFechaV());
             cmbtipo.setSelectedItem(p.getTipo());
            aux = 1;

        } else {
            txtNombre.requestFocusInWindow();
            aux = 0;

        }

        JButton botonesH[] = {cmdAgregar, cmdCancelar};
        JButton botonesD[] = {cmdBuscar, cmdEliminar};
        HelperInv.habilitarBotones(botonesH);
        HelperInv.deshabilitarBotones(botonesD);

    }//GEN-LAST:event_cmdBuscarActionPerformed
    public void limpiar() {
        txtMarca.setText("");
        txtNombre.setText("");
        txtCantidad.setText("");
        jDateChooser1.setDateFormatString("");
        cmbtipo.setSelectedIndex(0);
        
        txtMarca.requestFocusInWindow();
        aux = 0;
    }
    private void tblInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventarioMouseClicked
        Inventario p;
        int i;
        inventario = HelperInv.traerDatos2(rutaP);
        i = tblInventario.getSelectedRow();
        p = inventario.get(i);

        txtMarca.setText(p.getMarca());
        txtNombre.setText(p.getNombrep());
        txtCantidad.setText(p.getCantidad());
        jDateChooser1.setDateFormatString(p.getFechaV());
          cmbtipo.setSelectedItem(p.getTipo());
        aux = 1;
        JButton botonesH[] = {cmdEliminar, cmdAgregar, cmdCancelar};
        JButton botonesD[] = {cmdBuscar};
        HelperInv.habilitarBotones(botonesH);
        HelperInv.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_tblInventarioMouseClicked

    private void cmbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFechaActionPerformed
       String dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
       String mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH)+1);
       String año = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
       String fecha =(año + "/" + mes + "/" + dia);
       txtFecha.setText(fecha);
    }//GEN-LAST:event_cmbFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InventarioIn dialog = new InventarioIn(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbFecha;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventario;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
