/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/IconoG4.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdSalir = new javax.swing.JButton();
        jLabelLoginUser = new javax.swing.JLabel();
        jLabel1Password = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel1User1 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        cmdIniciar = new javax.swing.JButton();
        cmdRegistro = new javax.swing.JButton();
        jLabel1Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdSalir.setBackground(new java.awt.Color(0, 0, 51));
        cmdSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(255, 255, 255));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, -1));

        jLabelLoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personal.png"))); // NOI18N
        jPanel1.add(jLabelLoginUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 250, 250));

        jLabel1Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1Password.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1Password.setText("Contraseña:");
        jPanel1.add(jLabel1Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 51));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 200, -1));

        jLabel1User1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1User1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1User1.setText("Usuario:");
        jPanel1.add(jLabel1User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        txtContraseña.setBackground(new java.awt.Color(0, 0, 51));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, -1));

        cmdIniciar.setBackground(new java.awt.Color(0, 0, 51));
        cmdIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdIniciar.setForeground(new java.awt.Color(255, 255, 255));
        cmdIniciar.setText("Iniciar Sesión");
        cmdIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 140, -1));

        cmdRegistro.setBackground(new java.awt.Color(0, 0, 51));
        cmdRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdRegistro.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegistro.setText("Registrarse");
        cmdRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(cmdRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, -1));

        jLabel1Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1197772936,Longhorn-Wallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel1Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistroActionPerformed
     Registro abrir = new Registro(this,true);
        abrir.setVisible(true);
    }//GEN-LAST:event_cmdRegistroActionPerformed

    private void cmdIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIniciarActionPerformed
    Principal abrir = new Principal();  
    abrir.setVisible(true);
    this.setVisible(false);
    
        
    }//GEN-LAST:event_cmdIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdIniciar;
    private javax.swing.JButton cmdRegistro;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1Fondo;
    private javax.swing.JLabel jLabel1Password;
    private javax.swing.JLabel jLabel1User1;
    private javax.swing.JLabel jLabelLoginUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
