/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import clases.Validar;
import interfaces.Agregar;
import javax.swing.JOptionPane;
import interfaces.HorasExtras;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/**
 *
 * @author Lenovo
 */

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Validar v = new Validar();
    public Principal() {
        
        initComponents();
       
        this.setLocationRelativeTo(null);
        v.ValidarSoloNumeros(txtSueldoB);
        
        
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/IconoG4.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ARL = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2User = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2Sueldo = new javax.swing.JPanel();
        txtSueldoB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombrecom = new javax.swing.JLabel();
        txtDireccioncom = new javax.swing.JLabel();
        txtTelefonocom = new javax.swing.JLabel();
        txtCorreocom = new javax.swing.JLabel();
        txtFechacom = new javax.swing.JLabel();
        txtCargocom = new javax.swing.JLabel();
        txtCedulacom = new javax.swing.JLabel();
        cmdAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JLabel();
        txtAux = new javax.swing.JLabel();
        txtSaludE = new javax.swing.JLabel();
        txtPensionE = new javax.swing.JLabel();
        cmdHorasExtras = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtHorasExtras2 = new javax.swing.JTextField();
        txtHorasExtras1 = new javax.swing.JLabel();
        txtTotalD = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jNivel1 = new javax.swing.JRadioButton();
        jNivel2 = new javax.swing.JRadioButton();
        jNivel3 = new javax.swing.JRadioButton();
        jNivel4 = new javax.swing.JRadioButton();
        jNivel5 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        txtSaludA = new javax.swing.JLabel();
        txtPensionA = new javax.swing.JLabel();
        txtCaja = new javax.swing.JLabel();
        txtSena = new javax.swing.JLabel();
        txtICBF = new javax.swing.JLabel();
        txtARL = new javax.swing.JLabel();
        txtCesantias = new javax.swing.JLabel();
        txtPrimasS = new javax.swing.JLabel();
        txtVacaciones = new javax.swing.JLabel();
        txtInteresesC = new javax.swing.JLabel();
        cmdMostrar = new javax.swing.JButton();
        cmdExportar = new javax.swing.JButton();
        jLabel1fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ListadoEm = new javax.swing.JMenu();
        ListadoEmpleados = new javax.swing.JMenuItem();
        mnIngresarInv = new javax.swing.JMenu();
        IngresarInv = new javax.swing.JMenuItem();
        ListadoTipoProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2User.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel2User.setOpaque(false);
        jPanel2User.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        jPanel2User.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 54, 60, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula:");
        jPanel2User.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono:");
        jPanel2User.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");
        jPanel2User.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Correo:");
        jPanel2User.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cargo:");
        jPanel2User.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de Ingreso:");
        jPanel2User.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jPanel2Sueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2Sueldo.setOpaque(false);
        jPanel2Sueldo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSueldoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSueldoBKeyPressed(evt);
            }
        });
        jPanel2Sueldo.add(txtSueldoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingrese Salario Base:");
        jPanel2Sueldo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2User.add(jPanel2Sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 340, 60));
        jPanel2User.add(txtNombrecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 200, 20));
        jPanel2User.add(txtDireccioncom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 200, 20));
        jPanel2User.add(txtTelefonocom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 20));
        jPanel2User.add(txtCorreocom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 200, 20));
        jPanel2User.add(txtFechacom, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 200, 20));
        jPanel2User.add(txtCargocom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 200, 20));
        jPanel2User.add(txtCedulacom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 20));

        jPanel1.add(jPanel2User, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 550));

        cmdAgregar.setBackground(new java.awt.Color(0, 0, 51));
        cmdAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdAgregar.setForeground(new java.awt.Color(255, 255, 255));
        cmdAgregar.setText("AGREGAR");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 500, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vecaciones:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Primas de servicio:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cesantias:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Caja de compensacion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setFocusable(false);
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Salario:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Aux Transporte:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Salud:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Horas Extras  ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total Devengado:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 20));
        jPanel2.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 20));
        jPanel2.add(txtAux, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 20));
        jPanel2.add(txtSaludE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 160, 20));
        jPanel2.add(txtPensionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, 20));

        cmdHorasExtras.setBackground(new java.awt.Color(0, 0, 51));
        cmdHorasExtras.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdHorasExtras.setForeground(new java.awt.Color(255, 255, 255));
        cmdHorasExtras.setText("H");
        cmdHorasExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHorasExtrasActionPerformed(evt);
            }
        });
        jPanel2.add(cmdHorasExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Pension:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("y recargos:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtHorasExtras2.setText("0");
        jPanel2.add(txtHorasExtras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, 30));
        jPanel2.add(txtHorasExtras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));
        jPanel2.add(txtTotalD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 270, 220));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sena:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Pension:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ICBF:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ARL:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Salud:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jNivel1.setBackground(new java.awt.Color(0, 0, 51));
        ARL.add(jNivel1);
        jNivel1.setForeground(new java.awt.Color(255, 255, 255));
        jNivel1.setText("Nivel 1");
        jNivel1.setOpaque(false);
        jPanel1.add(jNivel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));

        jNivel2.setBackground(new java.awt.Color(0, 0, 51));
        ARL.add(jNivel2);
        jNivel2.setForeground(new java.awt.Color(255, 255, 255));
        jNivel2.setText("Nivel 2");
        jNivel2.setOpaque(false);
        jPanel1.add(jNivel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jNivel3.setBackground(new java.awt.Color(0, 0, 51));
        ARL.add(jNivel3);
        jNivel3.setForeground(new java.awt.Color(255, 255, 255));
        jNivel3.setText("Nivel 3");
        jNivel3.setOpaque(false);
        jPanel1.add(jNivel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, -1, -1));

        jNivel4.setBackground(new java.awt.Color(0, 0, 51));
        ARL.add(jNivel4);
        jNivel4.setForeground(new java.awt.Color(255, 255, 255));
        jNivel4.setText("Nivel 4");
        jNivel4.setOpaque(false);
        jPanel1.add(jNivel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jNivel5.setBackground(new java.awt.Color(0, 0, 51));
        ARL.add(jNivel5);
        jNivel5.setForeground(new java.awt.Color(255, 255, 255));
        jNivel5.setText("Nivel 5");
        jNivel5.setOpaque(false);
        jPanel1.add(jNivel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Intereses sobre cesantias:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));
        jPanel1.add(txtSaludA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 170, 20));
        jPanel1.add(txtPensionA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 160, 20));
        jPanel1.add(txtCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, 20));
        jPanel1.add(txtSena, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 140, 20));
        jPanel1.add(txtICBF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 130, 20));
        jPanel1.add(txtARL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 120, 20));
        jPanel1.add(txtCesantias, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 150, 20));
        jPanel1.add(txtPrimasS, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 140, 20));
        jPanel1.add(txtVacaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 140, 20));
        jPanel1.add(txtInteresesC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 280, 130, 20));

        cmdMostrar.setBackground(new java.awt.Color(0, 0, 51));
        cmdMostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdMostrar.setForeground(new java.awt.Color(255, 255, 255));
        cmdMostrar.setText("Calcular");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 200, -1));

        cmdExportar.setBackground(new java.awt.Color(0, 0, 51));
        cmdExportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmdExportar.setForeground(new java.awt.Color(255, 255, 255));
        cmdExportar.setText("Exportar");
        jPanel1.add(cmdExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 200, 130));

        jLabel1fondo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1197772936,Longhorn-Wallpaper.jpg"))); // NOI18N
        jPanel1.add(jLabel1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 51));
        jMenuBar1.setOpaque(false);

        jMenu1.setText("File");

        ListadoEm.setText("Listado");
        ListadoEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoEmActionPerformed(evt);
            }
        });

        ListadoEmpleados.setText("Empleados Listado");
        ListadoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoEmpleadosActionPerformed(evt);
            }
        });
        ListadoEm.add(ListadoEmpleados);

        jMenu1.add(ListadoEm);

        jMenuBar1.add(jMenu1);

        mnIngresarInv.setText("Inventario");
        mnIngresarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIngresarInvActionPerformed(evt);
            }
        });

        IngresarInv.setText("Ingresar a Inventario");
        IngresarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarInvActionPerformed(evt);
            }
        });
        mnIngresarInv.add(IngresarInv);

        ListadoTipoProducto.setText("Listado Tipo Producto");
        ListadoTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoTipoProductoActionPerformed(evt);
            }
        });
        mnIngresarInv.add(ListadoTipoProducto);

        jMenuBar1.add(mnIngresarInv);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  String nombre, cedula, telefono, direccion, correo,cargo,fechaIng,HorasExtras;
    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        this.dispose();   
        Agregar abrir = new Agregar (this,true);
        abrir.setVisible(true);
    
    
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void mnIngresarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIngresarInvActionPerformed
      
    }//GEN-LAST:event_mnIngresarInvActionPerformed

    private void IngresarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarInvActionPerformed
       InventarioIn a = new InventarioIn (this,true);
        a.setVisible(true);
    }//GEN-LAST:event_IngresarInvActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      txtNombrecom.setText(nombre);
      txtCedulacom.setText(cedula);
      txtTelefonocom.setText(telefono);
      txtDireccioncom.setText(direccion);
      txtCorreocom.setText(correo);
      txtCargocom.setText(cargo);
      txtFechacom.setText(fechaIng);
      txtHorasExtras1.setText(HorasExtras);
    }//GEN-LAST:event_formWindowActivated

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        double sueldoB,HorasE,pension,salud,saludA,pensionA,caja,sena,icbf,arl,cesantias,primas,vacaciones,intersesC,numd,totalSE,totalPE,totalSA,totalPA,totalD;
       String res;
       
       int aux;
       float r;
       
       
      
       
       
       if(txtSueldoB.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite sueldo base","Error", JOptionPane.ERROR_MESSAGE);
         txtSueldoB.requestFocusInWindow();
       }else{
           
        
        
         
       
       HorasE=Double.parseDouble(txtHorasExtras2.getText());
       sueldoB=Double.parseDouble(txtSueldoB.getText());
       
        if(sueldoB>=1378908){
            aux=0;
            
        }else{
            aux=77700;
        }
       
       
       totalSE=(sueldoB+HorasE)*0.04;
       totalPE=(sueldoB+HorasE)*0.04;
       totalSA=(sueldoB+HorasE)*0.085;
       totalPA=(sueldoB+HorasE)*0.012;
       totalD=sueldoB+aux+HorasE-totalSE-totalPE;
       caja=(sueldoB+HorasE)*0.04;
       sena=(sueldoB+HorasE)*0.02;
       icbf=(sueldoB+HorasE)*0.03;
       cesantias=(sueldoB+HorasE+aux)*0.08333333333333333333333333;
       primas=(sueldoB+HorasE+aux)*0.0833333333333333333333333;
       vacaciones=sueldoB*0.0417777777777777777;
       intersesC=cesantias*0.12;
       
       
       res=String.valueOf(sueldoB);
       txtSueldo.setText(res);
       
       res=String.valueOf(aux);
       txtAux.setText(res);
               
       res=String.valueOf(totalSE);
       txtSaludE.setText(res);
       res=String.valueOf(totalPE);
       txtPensionE.setText(res);
       res=String.valueOf(totalSA);
       txtSaludA.setText(res);
       res=String.valueOf(totalPA);
       txtPensionA.setText(res);
       res=String.valueOf(totalD);
       txtTotalD.setText(res);
       
       res=String.valueOf(caja);
       txtCaja.setText(res);
       
       res=String.valueOf(sena);
       txtSena.setText(res);
       
       res=String.valueOf(icbf);
       txtICBF.setText(res);
       
       res=String.valueOf(cesantias);
       txtCesantias.setText(res);
       
       res=String.valueOf(primas);
       txtPrimasS.setText(res);
       
       res=String.valueOf(vacaciones);
       txtVacaciones.setText(res);
       
       res=String.valueOf(intersesC);
       txtInteresesC.setText(res);
       
       
       
      
        sueldoB=Double.parseDouble(txtSueldoB.getText());
        
        if(jNivel1.getModel().isSelected()){
          r=(float) (sueldoB*0.00522);
          txtARL.setText(String.valueOf(r));        
      }
      if(jNivel2.getModel().isSelected()){
          r=(float) (sueldoB*0.01044);
          txtARL.setText(String.valueOf(r));        
      }
      if(jNivel3.getModel().isSelected()){
          r=(float) (sueldoB*0.02436);
          txtARL.setText(String.valueOf(r));        
      }
      if(jNivel4.getModel().isSelected()){
          r=(float) (sueldoB*0.04350);
          txtARL.setText(String.valueOf(r));        
      }
      if(jNivel5.getModel().isSelected()){
          r=(float) (sueldoB*0.06960);
          txtARL.setText(String.valueOf(r));        
      }
      
     }
      
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdHorasExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHorasExtrasActionPerformed
     HorasExtras abrir = new HorasExtras(this,true);
        abrir.setVisible(true);
    }//GEN-LAST:event_cmdHorasExtrasActionPerformed

    private void ListadoTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoTipoProductoActionPerformed
        ListadoTipoProducto abrir = new ListadoTipoProducto(this, true);
        abrir.setVisible(true);
    }//GEN-LAST:event_ListadoTipoProductoActionPerformed

    private void ListadoEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoEmActionPerformed
         
    }//GEN-LAST:event_ListadoEmActionPerformed

    private void ListadoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoEmpleadosActionPerformed
        ListadoEmpleados a = new ListadoEmpleados(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_ListadoEmpleadosActionPerformed

    private void txtSueldoBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoBKeyPressed
       
    }//GEN-LAST:event_txtSueldoBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup ARL;
    private javax.swing.JMenuItem IngresarInv;
    private javax.swing.JMenu ListadoEm;
    private javax.swing.JMenuItem ListadoEmpleados;
    private javax.swing.JMenuItem ListadoTipoProducto;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdExportar;
    private javax.swing.JButton cmdHorasExtras;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1fondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jNivel1;
    private javax.swing.JRadioButton jNivel2;
    private javax.swing.JRadioButton jNivel3;
    private javax.swing.JRadioButton jNivel4;
    private javax.swing.JRadioButton jNivel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2Sueldo;
    private javax.swing.JPanel jPanel2User;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu mnIngresarInv;
    private javax.swing.JLabel txtARL;
    private javax.swing.JLabel txtAux;
    private javax.swing.JLabel txtCaja;
    private javax.swing.JLabel txtCargocom;
    private javax.swing.JLabel txtCedulacom;
    private javax.swing.JLabel txtCesantias;
    private javax.swing.JLabel txtCorreocom;
    private javax.swing.JLabel txtDireccioncom;
    private javax.swing.JLabel txtFechacom;
    private javax.swing.JLabel txtHorasExtras1;
    public static javax.swing.JTextField txtHorasExtras2;
    private javax.swing.JLabel txtICBF;
    private javax.swing.JLabel txtInteresesC;
    private javax.swing.JLabel txtNombrecom;
    private javax.swing.JLabel txtPensionA;
    private javax.swing.JLabel txtPensionE;
    private javax.swing.JLabel txtPrimasS;
    private javax.swing.JLabel txtSaludA;
    private javax.swing.JLabel txtSaludE;
    private javax.swing.JLabel txtSena;
    private javax.swing.JLabel txtSueldo;
    private javax.swing.JTextField txtSueldoB;
    private javax.swing.JLabel txtTelefonocom;
    private javax.swing.JLabel txtTotalD;
    private javax.swing.JLabel txtVacaciones;
    // End of variables declaration//GEN-END:variables
}
